
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ojimenez
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: