
services:
  db:
    image: postgres:15
    container_name: postgres_data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: ojimenez
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - piscine_net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_data
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: orioljg2002@gmail.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - piscine_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  piscine_net:
    driver: bridge